# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 28) do

  create_table "counterworks", :force => true do |t|
    t.column "technician_id", :integer
    t.column "description",   :text
    t.column "created_at",    :datetime
  end

  create_table "customers", :force => true do |t|
    t.column "first_name",       :string
    t.column "last_name",        :string
    t.column "phone_number",     :string
    t.column "department",       :string
    t.column "alt_phone_number", :string
    t.column "email_address",    :string
  end

  create_table "links", :force => true do |t|
    t.column "title", :string
    t.column "link",  :string
  end

  create_table "manufacturers", :force => true do |t|
    t.column "name", :string
  end

  create_table "messages", :force => true do |t|
    t.column "message",     :text
    t.column "created_at",  :datetime
    t.column "sender_id",   :integer
    t.column "receiver_id", :integer
    t.column "opened",      :boolean
  end

  create_table "notes", :force => true do |t|
    t.column "technician_id", :integer
    t.column "note",          :text
    t.column "ticket_id",     :integer
    t.column "created_at",    :datetime
  end

  create_table "parts", :force => true do |t|
    t.column "status",          :string
    t.column "technician_id",   :integer
    t.column "ticket_id",       :integer
    t.column "part",            :string
    t.column "requested_at",    :datetime
    t.column "ordered_at",      :datetime
    t.column "shipped_at",      :datetime
    t.column "received_at",     :datetime
    t.column "tracking_number", :string
  end

  create_table "statuses", :force => true do |t|
    t.column "ticket_id", :integer
    t.column "key",       :string
  end

  create_table "technicians", :force => true do |t|
    t.column "initials",        :string
    t.column "name",            :string
    t.column "username",        :string
    t.column "hashed_password", :string
    t.column "password_hash",   :string
    t.column "admin",           :boolean
    t.column "enabled",         :boolean
  end

  create_table "tickets", :force => true do |t|
    t.column "problem",            :text
    t.column "created_at",         :datetime
    t.column "completed_at",       :datetime
    t.column "customer_id",        :integer
    t.column "unit_id",            :integer
    t.column "power_cord",         :boolean
    t.column "bag",                :boolean
    t.column "discs",              :boolean
    t.column "misc_accessories",   :string
    t.column "priority",           :boolean
    t.column "quote_number",       :string
    t.column "services_performed", :text
    t.column "parts",              :float
    t.column "labor",              :float
    t.column "picked_up",          :datetime
    t.column "claimed_by",         :integer
    t.column "taxable",            :boolean,  :default => true
    t.column "created_by",         :integer
  end

  create_table "types", :force => true do |t|
    t.column "name", :string
  end

  create_table "units", :force => true do |t|
    t.column "serial_number",   :string
    t.column "manufacturer_id", :integer
    t.column "type_id",         :integer
    t.column "customer_id",     :integer
    t.column "description",     :text
  end

  add_index "units", ["serial_number"], :name => "index_units_on_serial_number"

end
